"""Fix employee department_id unique constraint

Revision ID: 72177ca22887
Revises: fb9b040d6601
Create Date: 2026-05-24 15:24:34.400109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72177ca22887'
down_revision: Union[str, Sequence[str], None] = 'fb9b040d6601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('employees_department_id_key'), 'employees', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('employees_department_id_key'), 'employees', ['department_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
